Install Bundler 1.17.3 when latest version fails
Since Bundler 2.0 was released, `gem install bundler` fails on older
Ruby versions with the following error:

    ERROR:  Error installing bundler:
            bundler requires Ruby version >= 2.3.0.